nlu:
  url: http://rasa_nlu:5000

action_endpoint:
  url: http://action_server:5055/webhook

tracker_store:
  store_type: mongod
  url: mongodb://192.168.0.160:27017
  username: rasa
  password: example
