# The model server is specified in the endpoint configuration (my_endpoints.yaml), 
# where you specify the server URL Rasa Core regularly queries for zipped Rasa Core models:

models:
  url: http://another-rasa-coreserver.org/models/default_core@latest
  wait_time_between_pulls:  100   # [optional](default: 100)
