version: '3.0'

services:

  rasa_core:
    image: rasa/rasa_core:latest
    container_name: rasa_core
    ports:
      - 5005:5005
    volumes:
      - ./project:/app/project
      - ./project/models/core:/app/models
      - ./project/config:/app/config
    command:
      - start
      - --core
      - models
      - -c
      - rest
      - --endpoints
      - config/endpoints.yml
      - -u
      - current/

  rasa_nlu:
    image: rasa/rasa_nlu:latest-spacy
#   image: rasa/rasa_nlu:latest-full
    container_name: rasa_nlu
    ports:
      - 5000:5000
    volumes:
      - ./project:/app/project
      - ./project/models/nlu:/app/model
      - ./project/config:/app/config
    command:
      - start
      - --path
      - models

  action_server:
    image: rasa/rasa_core_sdk:latest
    container_name: rasa_action_server
    ports:
      - 5055:5055
    volumes:
      - ./project/actions:/app/actions

  mongo:
    image: mongo
    container_name: rasa_mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: rasa
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express
    container_name: rasa_mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: rasa
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
    depends_on:
      - mongo

