version: '3.0'

services:

  rasa_core:
    image: rasa/rasa_core:latest
    container_name: rasa_core
    ports:
      - 5005:5005
    volumes:
      - ./projects:/app/projects
      - ./projects/models/core:/app/models
      - ./projects/config:/app/config
      - ./projects/logs:/app/logs
      - ./projects/data:/app/data
    command:
      - start
      - --core
      - models
      - -c
      - rest
      - --endpoints
      - config/endpoints.yml
      - -u
      - nlu_model

  rasa_nlu:
    image: rasa/rasa_nlu:latest-spacy
#    image: rasa/rasa_nlu:latest-full
    container_name: rasa_nlu
    ports:
      - 5000:5000
    volumes:
      - ./projects:/app/projects
      - ./projects/models/nlu:/app/models
      - ./projects/config:/app/config
      - ./projects/logs:/app/logs
      - ./projects/data:/app/data
    command:
      - start
      - --path
      - models

  # Proxy for 4 Containers of Rasa-NLU to provide scalability
#  nginx:
#    image: nginx:mainline-alpine
#    ports:
#      - "5080:80"
#    volumes:
#      - "./nginx/nginx.conf:/etc/nginx/nginx.conf:ro"
#    links:
#      - rasa_nlu
      
  action_server:
    image: rasa/rasa_core_sdk:latest
    container_name: rasa_action_server
    ports:
      - 5055:5055
    volumes:
      - ./projects/actions:/app/actions

  mongo:
    image: mongo
    container_name: rasa_mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: rasa
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express
    container_name: rasa_mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: rasa
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
    depends_on:
      - mongo

